<!DOCTYPE html>

<html lang="en">

<head>

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-189356072-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-189356072-1');
  </script>


  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!--SEO PRIMARY META-->
  <meta name="title" content="Contact Us - CineCopters | Drone Filming Belfast, Northern Ireland & Dublin, Ireland">
  <meta name="description" content="If you have any question about drone filming in Belfast, Dublin or anywhere in Northern Ireland / Ireland or would like to book a drone crew please get in touch!" />

  <!--OPEN GRAPH AND FB META-->
  <meta property="og:type" content="website">
  <meta property="og:url" content="https://cinecopters.co.uk/contact">
  <meta property="og:title" content="Contact Us - CineCopters | Drones for Film &amp; TV">
  <meta property="og:image" content="/img/office5.jpg">
  <meta property="og:description" content="If you have any question about drone filming in Belfast, Dublin or anywhere in Northern Ireland / Ireland or would like to book a drone crew please get in touch!">

  <!-- TWITTER META -->
  <meta property="twitter:card" content="summary_large_image">
  <meta property="twitter:url" content="https://cinecopters.co.uk/contact">
  <meta property="twitter:title" content="Contact Us - CineCopters | Drone Filming Belfast, Northern Ireland & Dublin, Ireland">
  <meta property="twitter:description" content="If you have any question about drone filming in Belfast, Dublin or anywhere in Northern Ireland / Ireland or would like to book a drone crew please get in touch!">
  <meta property="twitter:image" content="/img/office5.jpg">

  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "CineCopters",
  "telephone" : [ "Belfast | +4428 90 4482 86", "Dublin | +353 1486 9770", "Glasgow | +44 141 459 0259", "Technical | +4475 402 51374", "Technical | +4477 805 86444" ],
  "email" : [ "info@cinecopters.co.uk", "accounts@cinemedia.ie" ]
}
</script>

  <!-- The above meta tags *must* come first in the head; any other head content must come *after* these tags -->

  <title>Contact Us - CineCopters | Belfast Northern Ireland - Dublin Ireland</title>