<!DOCTYPE html>

<html lang="en">

<head>

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-189356072-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-189356072-1');
  </script>


  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!--SEO PRIMARY META-->
  <meta name="title" content="CineCopters | Drone Filming Belfast, Northern Ireland & Dublin, Ireland">
  <meta name="description" content="CineCopters based in Belfast, Northern Ireland and Dublin, Ireland has over 10 years experience in drone filming for feature films, TV drama and broadcast television.  A BBC, ITV, Netflix, Universal & Disney preferred supplier." />

  <!--OPEN GRAPH AND FB META-->
  <meta property="og:type" content="website">
  <meta property="og:url" content="https://cinecopters.co.uk/">
  <meta property="og:title" content="CineCopters | Drones for Film &amp; TV">
  <meta property="og:image" content="/img/showreelimagescopy.jpg">
  <meta property="og:description" content="The premiere drone filming company base in Belfast, Northern Ireland &amp; Dublin, Ireland. | FILM - TELEVISION -  COMMERCIAL">

  <!-- TWITTER META -->
  <meta property="twitter:card" content="summary_large_image">
  <meta property="twitter:url" content="https://cinecopters.co.uk/">
  <meta property="twitter:title" content="CineCopters | Drone Filming Belfast, Northern Ireland & Dublin, Ireland">
  <meta property="twitter:description" content="The premiere drone filming company base in Belfast, Northern Ireland & Dublin, Ireland. | FILM - TELEVISION -  COMMERCIAL">
  <meta property="twitter:image" content="/img/showreelimagescopy.jpg">

  <link rel="canonical" href="https://cinecopters.co.uk/">

  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[ {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Drones for Film & TV",
  "telephone" : [ "+4428 90 4482 86", "+353 1486 9770", "+44 141 459 0259", "+4477 805 86444", "+4475 402 51374" ],
  "email" : "info@cinecopters.co.uk",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : "Belfast, Northern Ireland"
  },
  "url" : "https://cinecopters.co.uk/index.php",
  "review" : {
    "@type" : "Review",
    "author" : {
      "@type" : "Person",
      "name" : "HBO - AMC - Universal Pictures - Film 4 - Scott Free Productions - Netflix - Microsoft - MTV - BBC - Discovery"
    }
  }
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Drones for Film & TV",
  "telephone" : [ "+4428 90 4482 86", "+353 1486 9770", "+44 141 459 0259", "+4477 805 86444", "+4475 402 51374" ],
  "email" : "info@cinecopters.co.uk",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : "Belfast, Northern Ireland"
  },
  "url" : "https://cinecopters.co.uk/index.php",
  "review" : {
    "@type" : "Review",
    "author" : {
      "@type" : "Person",
      "name" : "Stacey James - Producer"
    },
    "reviewBody" : "Better than a f*ckin&#39; helicopter! <BR/>Oh My God...”"
  }
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Drones for Film & TV",
  "telephone" : [ "+4428 90 4482 86", "+353 1486 9770", "+44 141 459 0259", "+4477 805 86444", "+4475 402 51374" ],
  "email" : "info@cinecopters.co.uk",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : "Belfast, Northern Ireland"
  },
  "review" : {
    "@type" : "Review",
    "author" : {
      "@type" : "Person",
      "name" : "Stacey James - Producer"
    },
    "reviewBody" : "“A calm and professional approach, incredibly competitive rates and the ability to deliver utterly breathtaking shots. Exec Producers from Canada, New York and beyond were amazed. Highly recommended”"
  }
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Drones for Film & TV",
  "telephone" : [ "+4428 90 4482 86", "+353 1486 9770", "+44 141 459 0259", "+4477 805 86444", "+4475 402 51374" ],
  "email" : "info@cinecopters.co.uk",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : "Belfast, Northern Ireland"
  },
  "review" : {
    "@type" : "Review",
    "author" : {
      "@type" : "Person",
      "name" : "Glen Collins - Producer"
    },
    "reviewBody" : "“CineMedia &amp; CineCopters are at the top of their game and I can highly recommend them to anyone looking for first-class filming in Ireland. Having worked with them all around the country over the past 5 years, on all kinds of productions, their calm and professional approach is second to none. The footage they deliver is always above and beyond what the director is looking for. We were really impressed by the high standard of service, professionalism, and superb quality of"
  }
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Drones for Film & TV",
  "telephone" : [ "+4428 90 4482 86", "+353 1486 9770", "+44 141 459 0259", "+4477 805 86444", "+4475 402 51374" ],
  "email" : "info@cinecopters.co.uk",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : "Belfast, Northern Ireland"
  },
  "review" : {
    "@type" : "Review",
    "author" : {
      "@type" : "Person",
      "name" : "Michael Lennox - Director"
    },
    "reviewBody" : "“The speed and efficiency of the guys blew me away. I found myself making up more shots because it took no time to get exactly what"
  }
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Drones for Film & TV",
  "telephone" : [ "+4428 90 4482 86", "+353 1486 9770", "+44 141 459 0259", "+4477 805 86444", "+4475 402 51374" ],
  "email" : "info@cinecopters.co.uk",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : "Belfast, Northern Ireland"
  },
  "review" : {
    "@type" : "Review",
    "author" : {
      "@type" : "Person",
      "name" : "Orla Bleahen - Producer"
    },
    "reviewBody" : "“Their work was exemplary as always and the Directors and clients were over the moon with the work they did - everyone was singing their praises. And as for getting me out of the bind - I so so appreciate it. I always say you guys are the best and your lads"
  }
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Drones for Film & TV",
  "telephone" : [ "+4428 90 4482 86", "+353 1486 9770", "+44 141 459 0259", "+4477 805 86444", "+4475 402 51374" ],
  "email" : "info@cinecopters.co.uk",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : "Belfast, Northern Ireland"
  },
  "review" : {
    "@type" : "Review",
    "author" : {
      "@type" : "Person",
      "name" : "George Pagliero"
    },
    "reviewBody" : "I cannot speak more highly of CineMedia’s and CineCopters approach to filming... Communication between BBC production and their crew was excellent throughout; they worked just as happily overseen by our director as independently to a brief... Absolutely stunning (the opening shots of the show are to die for). Having worked with over a dozen drone and ground crews in the last few years I can confidently say they are at the top of their game and recommend them to anyone looking for first class company in Ireland...”"
  }
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Drones for Film & TV",
  "telephone" : [ "+4428 90 4482 86", "+353 1486 9770", "+44 141 459 0259", "+4477 805 86444", "+4475 402 51374" ],
  "email" : "info@cinecopters.co.uk",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : "Belfast, Northern Ireland"
  },
  "review" : {
    "@type" : "Review",
    "author" : {
      "@type" : "Person",
      "name" : "Joan Lambur - MD / Producer"
    },
    "reviewBody" : "We couldn’t have been happier with the beautiful footage CineMedia / CineCopters captured. It’s taken our series to a whole new level. They were easy to work with and came through for us in spite of a tight"
  }
} ]
</script>

  <!-- The above meta tags *must* come first in the head; any other head content must come *after* these tags -->

  <title>CineCopters | Drones for Film &amp; TV | Belfast Northern Ireland - Dublin Ireland</title>