<!DOCTYPE html>

<html lang="en">

<head>

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-189356072-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-189356072-1');
  </script>


  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!--SEO PRIMARY META-->
  <meta name="title" content="About Us - CineCopters | Drone Filming Belfast, Northern Ireland & Dublin, Ireland">
  <meta name="description" content="Over 50 years of film and television experience in Belfast Northern Ireland and Dublin Ireland and 10 years drone filming makes us the key BBC preferred supplier in Northern Ireland."/>

  <!--OPEN GRAPH AND FB META-->
  <meta property="og:type" content="website">
  <meta property="og:url" content="https://cinecopters.co.uk/about">
  <meta property="og:title" content="About Us - CineCopters | Drones for Film &amp; TV">
  <meta property="og:image" content="/img/vulcan4.jpg">
  <meta property="og:description" content="Over 50 years of film and television experience in Belfast Northern Ireland and Dublin Ireland and 10 years drone filming makes us the key BBC preferred supplier in Northern Ireland.">

  <!-- TWITTER META -->
  <meta property="twitter:card" content="summary_large_image">
  <meta property="twitter:url" content="https://cinecopters.co.uk/about">
  <meta property="twitter:title" content="About Us - CineCopters | Drone Filming Belfast, Northern Ireland & Dublin, Ireland">
  <meta property="twitter:description" content="Over 50 years of film and television experience in Belfast Northern Ireland and Dublin Ireland and 10 years drone filming makes us the key BBC preferred supplier in Northern Ireland.">
  <meta property="twitter:image" content="/img/vulcan4.jpg">

  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[ {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "drone filming",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : "Belfast",
    "addressCountry" : ", Northern Ireland"
  },
  "review" : {
    "@type" : "Review",
    "author" : {
      "@type" : "Person",
      "name" : "BBC"
    },
    "reviewRating" : {
      "@type" : "Rating",
      "ratingValue" : "preferred supplier"
    }
  }
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "drone filming",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : "Belfast",
    "addressCountry" : "Ireland"
  },
  "review" : {
    "@type" : "Review",
    "author" : {
      "@type" : "Person",
      "name" : "BBC"
    },
    "reviewRating" : {
      "@type" : "Rating",
      "ratingValue" : "preferred supplier"
    }
  }
}, {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "drone filming",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : "Belfast",
    "addressCountry" : "UK"
  },
  "review" : {
    "@type" : "Review",
    "author" : {
      "@type" : "Person",
      "name" : "BBC"
    },
    "reviewRating" : {
      "@type" : "Rating",
      "ratingValue" : "preferred supplier"
    }
  }
} ]
</script>

  <!-- The above meta tags *must* come first in the head; any other head content must come *after* these tags -->

  <title>The Oner - CineCopters | Belfast Northern Ireland - Dublin Ireland</title>